name: 'Generate Arch Repo database and upload'
inputs:
  dest_path:
    required: true
  repo_name:
    required: true
#  gpg-privatekey:
#    description: 'Your GPG private key, used to sign repo.'
  local_path:
    default: './'
runs:
  using: 'docker'
  image: 'Dockerfile'
  
  env:
    dest_path: ${{ inputs.dest_path }}
    repo_name: ${{ inputs.repo_name }}
#    gpg_key: ${{ inputs.gpg-privatekey }}
    local_path: ${{ inputs.local_path }}
