name: BUILD

on:
  watch:
    types: [started]
  schedule:
  - cron: '1 */24 * * *'

jobs:
  buildAUR:
    strategy:
      matrix:
#        - lx-music
        include:
          - repos: git-cola
            preinstall-pkgs: "at-spi2-core"
          - repos: realesrgan-ncnn-vulkan
            preinstall-pkgs: "vulkan-intel"

      fail-fast: false
      
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - uses: ./build-aur-action
      with:
        repo-name: ${{ matrix.repos }}
        preinstallPkgs: ${{ matrix.preinstall-pkgs }}
    
    - uses: actions/upload-artifact@v3
      with:
        path: ./*/*.pkg.tar.zst
        name: ${{ matrix.repos }}
        if-no-files-found: error


  buildNonAUR:
    strategy:
      matrix:
        PKGBUILDs: [plantsvszombies, pvz_beta]

      fail-fast: false
      
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Non-AUR packages
        id: makepkg
        uses: ./build-nonaur-action
        with:
          pkgdir: ${{ matrix.PKGBUILDs }}
          aurDeps: true
          
      - uses: actions/upload-artifact@v3
        with:
          path: ./*/*.pkg.tar.zst
          name: ${{ matrix.PKGBUILDs }}
          if-no-files-found: error


  uploadToReleases:
    if: always()
    needs:
    - buildAUR
    - buildNonAUR
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: download
      uses: actions/download-artifact@v2
    - uses: ./create-db-and-upload-action
      with:
        dest_path: /arch-pkg
        local_path: ${{ steps.download.outputs.download-path }}
        repo_name: zzy-ac
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ./*/*.zst,./*/zzy-ac.*
        tag: x86_64
        token: ${{ secrets.MY_GITHUB_TOKEN }}
